"""add contest models

Revision ID: 7786b4255e7c
Revises: ec865aadcdb1
Create Date: 2026-03-16 15:56:35.546678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7786b4255e7c'
down_revision: Union[str, None] = 'ec865aadcdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_submission_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_participants_contest_id'), 'contest_participants', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_participants_id'), 'contest_participants', ['id'], unique=False)
    op.create_index(op.f('ix_contest_participants_user_id'), 'contest_participants', ['user_id'], unique=False)
    op.create_table('contest_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_problems_contest_id'), 'contest_problems', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_problems_id'), 'contest_problems', ['id'], unique=False)
    op.create_index(op.f('ix_contest_problems_problem_id'), 'contest_problems', ['problem_id'], unique=False)
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('contest_type', sa.Enum('PUBLIC', 'PRIVATE', name='contesttype'), nullable=False),
    sa.Column('rule_type', sa.Enum('ACM', 'OI', name='ruletype'), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('real_time_rank', sa.Boolean(), nullable=False),
    sa.Column('freeze_time', sa.Integer(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_created_by'), 'contests', ['created_by'], unique=False)
    op.create_index(op.f('ix_contests_end_time'), 'contests', ['end_time'], unique=False)
    op.create_index(op.f('ix_contests_id'), 'contests', ['id'], unique=False)
    op.create_index(op.f('ix_contests_start_time'), 'contests', ['start_time'], unique=False)
    op.create_index(op.f('ix_contests_title'), 'contests', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contests_title'), table_name='contests')
    op.drop_index(op.f('ix_contests_start_time'), table_name='contests')
    op.drop_index(op.f('ix_contests_id'), table_name='contests')
    op.drop_index(op.f('ix_contests_end_time'), table_name='contests')
    op.drop_index(op.f('ix_contests_created_by'), table_name='contests')
    op.drop_table('contests')
    op.drop_index(op.f('ix_contest_problems_problem_id'), table_name='contest_problems')
    op.drop_index(op.f('ix_contest_problems_id'), table_name='contest_problems')
    op.drop_index(op.f('ix_contest_problems_contest_id'), table_name='contest_problems')
    op.drop_table('contest_problems')
    op.drop_index(op.f('ix_contest_participants_user_id'), table_name='contest_participants')
    op.drop_index(op.f('ix_contest_participants_id'), table_name='contest_participants')
    op.drop_index(op.f('ix_contest_participants_contest_id'), table_name='contest_participants')
    op.drop_table('contest_participants')
    # ### end Alembic commands ###
